// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/protobuf/admin/admin.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Admin struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Profilepic           string   `protobuf:"bytes,5,opt,name=profilepic,proto3" json:"profilepic,omitempty"`
	About                string   `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_13aead06b7159a35, []int{0}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Admin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Admin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Admin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Admin) GetProfilepic() string {
	if m != nil {
		return m.Profilepic
	}
	return ""
}

func (m *Admin) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func init() {
	proto.RegisterType((*Admin)(nil), "admin.Admin")
}

func init() { proto.RegisterFile("lib/protobuf/admin/admin.proto", fileDescriptor_13aead06b7159a35) }

var fileDescriptor_13aead06b7159a35 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xc9, 0x4c, 0xd2,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x83, 0x90,
	0x7a, 0x60, 0x41, 0x21, 0x56, 0x30, 0x47, 0x69, 0x32, 0x23, 0x17, 0xab, 0x23, 0x88, 0x25, 0xc4,
	0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0x22, 0x24,
	0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x16, 0x85, 0xf3,
	0x85, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc1, 0x12, 0x10, 0x8e, 0x90,
	0x10, 0x17, 0x0b, 0x58, 0x35, 0x0b, 0x58, 0x10, 0xcc, 0x16, 0x92, 0xe3, 0xe2, 0x2a, 0x28, 0xca,
	0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xc8, 0x4c, 0x96, 0x60, 0x05, 0xcb, 0x20, 0x89, 0x80, 0x4c, 0x4a,
	0x4c, 0xca, 0x2f, 0x2d, 0x91, 0x60, 0x83, 0x98, 0x04, 0xe6, 0x24, 0xb1, 0x81, 0xdd, 0x68, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xc4, 0x83, 0x4f, 0xc5, 0x00, 0x00, 0x00,
}
