// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/protobuf/blog/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	admin "lib/protobuf/admin"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DocType int32

const (
	DocType_MARKDOWN DocType = 0
	DocType_HTML     DocType = 1
)

var DocType_name = map[int32]string{
	0: "MARKDOWN",
	1: "HTML",
}

var DocType_value = map[string]int32{
	"MARKDOWN": 0,
	"HTML":     1,
}

func (x DocType) String() string {
	return proto.EnumName(DocType_name, int32(x))
}

func (DocType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_552ad2f0289e8f49, []int{0}
}

type Blog struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string               `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Author               *admin.Admin         `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	FormattedDate        string               `protobuf:"bytes,6,opt,name=formattedDate,proto3" json:"formattedDate,omitempty"`
	Sourcetype           DocType              `protobuf:"varint,7,opt,name=sourcetype,proto3,enum=blog.DocType" json:"sourcetype,omitempty"`
	Source               string               `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Thumbnail            string               `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IsPublic             bool                 `protobuf:"varint,11,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	IsDeleted            bool                 `protobuf:"varint,12,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_552ad2f0289e8f49, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Blog) GetAuthor() *admin.Admin {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Blog) GetFormattedDate() string {
	if m != nil {
		return m.FormattedDate
	}
	return ""
}

func (m *Blog) GetSourcetype() DocType {
	if m != nil {
		return m.Sourcetype
	}
	return DocType_MARKDOWN
}

func (m *Blog) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Blog) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Blog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Blog) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *Blog) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func init() {
	proto.RegisterEnum("blog.DocType", DocType_name, DocType_value)
	proto.RegisterType((*Blog)(nil), "blog.Blog")
}

func init() { proto.RegisterFile("lib/protobuf/blog/blog.proto", fileDescriptor_552ad2f0289e8f49) }

var fileDescriptor_552ad2f0289e8f49 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4b, 0x6b, 0xea, 0x40,
	0x14, 0xbe, 0xd1, 0x18, 0x93, 0xe3, 0x03, 0x19, 0x2e, 0x97, 0x21, 0xc8, 0x6d, 0x5a, 0x5c, 0x84,
	0x42, 0x23, 0xd8, 0x4d, 0xb7, 0x96, 0x2c, 0x0a, 0xad, 0x6d, 0x09, 0x42, 0xd7, 0x79, 0x8c, 0x71,
	0x60, 0xe2, 0x84, 0xe4, 0x64, 0xe1, 0x0f, 0xe8, 0xff, 0x2e, 0x99, 0xd1, 0x46, 0x37, 0x87, 0xf9,
	0x1e, 0xf3, 0x1d, 0xce, 0x07, 0x73, 0xc1, 0x93, 0x65, 0x59, 0x49, 0x94, 0x49, 0xb3, 0x5b, 0x26,
	0x42, 0xe6, 0x6a, 0x04, 0x8a, 0x22, 0x66, 0xfb, 0x76, 0x6f, 0x72, 0x29, 0x73, 0xc1, 0x3a, 0x1b,
	0xf2, 0x82, 0xd5, 0x18, 0x17, 0xa5, 0xb6, 0xb9, 0xff, 0xaf, 0x42, 0xe2, 0xac, 0xe0, 0x07, 0x3d,
	0xb5, 0x7e, 0xf7, 0xdd, 0x07, 0xf3, 0x59, 0xc8, 0x9c, 0x4c, 0xa1, 0xc7, 0x33, 0x6a, 0x78, 0x86,
	0xef, 0x44, 0x3d, 0x9e, 0x91, 0x19, 0xf4, 0x9b, 0x4a, 0xd0, 0x9e, 0x22, 0xda, 0x27, 0x59, 0x80,
	0x15, 0x37, 0xb8, 0x97, 0x15, 0xed, 0x7b, 0x86, 0x3f, 0x5a, 0x8d, 0x03, 0x1d, 0xb4, 0x6e, 0x67,
	0x74, 0xd2, 0xc8, 0x5f, 0x18, 0x20, 0x47, 0xc1, 0xa8, 0xa9, 0x7e, 0x6a, 0x40, 0x3c, 0x18, 0x65,
	0xac, 0x4e, 0x2b, 0x5e, 0x22, 0x97, 0x07, 0x3a, 0x50, 0xda, 0x25, 0x45, 0x16, 0x30, 0xd9, 0xc9,
	0xaa, 0x88, 0x11, 0x59, 0x16, 0xc6, 0xc8, 0xa8, 0xa5, 0x3c, 0xd7, 0x24, 0x79, 0x00, 0xa8, 0x65,
	0x53, 0xa5, 0x0c, 0x8f, 0x25, 0xa3, 0x43, 0xcf, 0xf0, 0xa7, 0xab, 0x49, 0xa0, 0x6a, 0x09, 0x65,
	0xba, 0x3d, 0x96, 0x2c, 0xba, 0x30, 0x90, 0x7f, 0x60, 0x69, 0x44, 0x6d, 0x95, 0x76, 0x42, 0x64,
	0x0e, 0x0e, 0xee, 0x9b, 0x22, 0x39, 0xc4, 0x5c, 0x50, 0x47, 0x49, 0x1d, 0x41, 0x9e, 0xc0, 0x49,
	0x2b, 0x16, 0x23, 0xcb, 0xd6, 0x48, 0x41, 0xdd, 0xea, 0x06, 0xba, 0xe8, 0xe0, 0x5c, 0x65, 0xb0,
	0x3d, 0x17, 0x1d, 0x75, 0x66, 0xe2, 0x82, 0xcd, 0xeb, 0xcf, 0x26, 0x11, 0x3c, 0xa5, 0x23, 0xcf,
	0xf0, 0xed, 0xe8, 0x17, 0xb7, 0x3b, 0x79, 0x1d, 0x32, 0xc1, 0x90, 0x65, 0x74, 0xac, 0xc4, 0x8e,
	0xb8, 0xbf, 0x85, 0xe1, 0xe9, 0x00, 0x32, 0x06, 0x7b, 0xb3, 0x8e, 0x5e, 0xc3, 0x8f, 0xaf, 0xf7,
	0xd9, 0x1f, 0x62, 0x83, 0xf9, 0xb2, 0xdd, 0xbc, 0xcd, 0x8c, 0xc4, 0x52, 0xbb, 0x1f, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x62, 0x92, 0x19, 0x18, 0x02, 0x00, 0x00,
}
